language: python
python:
# - "2.5"    Python 2.5 no longer supported by Travis CI
  - "2.6"
  - "2.7"
#  - "3.1"   Python 3.1 no longer supported by Travic CI
  - "3.2"
  - "3.3"
#   - "3.4"# Python 3.4 not yet available on Travis
  - "pypy"

# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: 
- python run_unit_tests.py
- python run_func_tests.py -v
